name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Gera a animação todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: Halwyr
          outputs: dist/snake.svg

      - name: Push generated snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

